### ISSUE TITLE
keyError:3200000

### ISSUE THREAD

**Issue by wanqiufenglv** [ymcui/Chinese-ELECTRA#50]
Traceback (most recent call last):
  File "run_finetuning.py", line 375, in <module>
    main()
  File "run_finetuning.py", line 371, in main
    args.model_name, args.data_dir, **hparams))
  File "run_finetuning.py", line 304, in run_finetuning
    scorer.write_predictions()
  File "/Chinese-ELECTRA-master/finetune/qa/qa_metrics.py", line 113, in write_predictions
    result = unique_id_to_result[feature[self._name + "_eid"]]
KeyError: 3200000

**Comment by nlper27149** [comment]
@wanqiufenglv  i met same error ,have you solved it?
